### ISSUE TITLE
Cannot create IdentityPolicy with Principal Service

### ISSUE THREAD

**Issue by danielvijge** [binxio/cfn-ses-provider#17]
In version 0.7.0 it is not possible to create an IdentityPolicy with an AWS service as the principal.

Example of such a policy
```yaml
  IdentityPolicy:
    Type: Custom::IdentityPolicy
    Properties:
      Identity: !GetAtt 'DomainIdentity.Domain'
      PolicyName: AllowMailFromCognito
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: !Sub 'arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${DomainIdentity.Domain}'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'
```

This fails with the error message in CloudFormation:
`Received response status [FAILED] from custom resource. Message returned: invalid resource properties: <instance> is not valid under any of the given schemas`

The schema in https://github.com/binxio/cfn-ses-provider/blob/master/src/identity_policy_provider.py#L38 only allows for `AWS`, but not for `Service`
