### ISSUE TITLE
Does not support multiple regions

### ISSUE THREAD

**Issue by discobean** [binxio/cfn-ses-provider#6]
Hi,

Great tool, however deploying in multiple regions with the same DNS name it fails to update the TXT record adding the new txt entry with the information.  It looks to just do a create only, and fails if it exists.

The CFN error is below:
```
[Tried to create resource record set [name='_amazonses.domain.name.', type='TXT'] 
but it already exists]
```

I'm guessing the same issue exists for DKIM records, but it never got to that step to check.

**Comment by mvanholsteijn** [comment]
Hi @discobean when requesting certificates in different regions, you must sure that you only create the DNS validation records for them in one region. DNS is a global variabele and the required DNS records are the same for each region: hence the error.

For DKIM, the situation is slighly different as each SES region generates different records to insert.

I trust this solves your problem.

**Comment by discobean** [comment]
Hey, thanks for getting back so quick!  That is what I thought too (like with SSL cert verification in cert manager), but I found that the TXT records required to verify the same domain across different regions was different, so it still does not help.

**Comment by mvanholsteijn** [comment]
I am sorry, i was :-(

**Comment by mvanholsteijn** [comment]
DKIM does not have that problem as it will generate unique entries in your zone.

**Comment by discobean** [comment]
All Good :) I ended up just working around with a different dns name for each region adding AWS::Region as part of the name.  This wasn't an issue for our use case.

**Comment by mvanholsteijn** [comment]
```
  DomainIdentity:
    Type: Custom::DomainIdentity
    Properties:
      Domain: !Ref 'DomainName'
      Region: !Ref 'AWS::Region'
      RecordSetDefaults:
        TTL: 60
        Weight: 1
        SetIdentifier: !Ref 'AWS::Region'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'


```
